CREATE SEQUENCE SESSION_ID_SEQ MINVALUE 0    START 0; --
CREATE SEQUENCE SCRAPING_ID_SEQ MINVALUE 0        START 0; --
CREATE SEQUENCE MORPHEME_ID_SEQ MINVALUE 0        START 0; --
CREATE SEQUENCE DICTIONARY_ID_SEQ MINVALUE 0        START 0; --
CREATE SEQUENCE KMEASN_ID_SEQ MINVALUE 0        START 0; --
CREATE SEQUENCE CASTLE_PART_DIC_ID_SEQ MINVALUE 0        START 0; --
CREATE SEQUENCE CASTLE_CONSTRUCTION_ID_SEQ MINVALUE 0         START 0; --
