source ../env.sh
 
psql -d ${DB_NAME} -U interest -c "select MORPHEME_ID, substr(WORD,1,20), SCRAPING_ID, COUNT from MORPHEMEANALYSIS WHERE SESSION_ID = 1 ORDER BY MORPHEME_ID DESC"
#psql -d ${DB_NAME} -U interest -c "select MORPHEME_ID, substr(WORD,1,20), SCRAPING_ID, COUNT from MORPHEMEANALYSIS WHERE SESSION_ID = 1 AND SCRAPING_ID = 2 ORDER BY MORPHEME_ID DESC"
